"""add device auth code table

Revision ID: 373924c30468
Revises: d028a621bc49
Create Date: 2026-08-16 23:45:59.189490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373924c30468'
down_revision: Union[str, Sequence[str], None] = 'd028a621bc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bd_device_auth_mt',
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bd_log.bd_usr_mt.id'], name='fk_device_auth_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_code'),
    sa.UniqueConstraint('user_code'),
    schema='bd_log'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bd_device_auth_mt', schema='bd_log')
    # ### end Alembic commands ###
